### ISSUE TITLE
More Info link is wrong

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_MAX1704X#2]
The arduino ide library panel has a More Info link for each library, the one for this library goes to https://github.com/adafruit/Adafruit_MAX17048 instead of with an X at the end rather than 8.

Thanks and keep up the good work!

P.S. would also be lovely if the https://learn.adafruit.com/adafruit-esp32-s2-tft-feather/factory-shipped-demo demo for the s2+s3's can be updated to do either LTxxx or MAX17xxxx ❤️

**Comment by caternuson** [comment]
Thanks. This was fixed by #1 and will be in the next release.

**Comment by tyeth** [comment]
Closed with v1.0.1
